// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type wakeCommKey struct {
	_    structs.HostLayout
	Comm [16]int8
}

type wakeOpenPending struct {
	_     structs.HostLayout
	Flags uint64
	Path  [256]int8
	Trunc uint8
	_     [7]byte
}

type wakePathKey struct {
	_      structs.HostLayout
	Prefix [64]int8
}

type wakeWakeCfg struct {
	_              structs.HostLayout
	SelfPid        uint64
	CgroupScope    uint64
	ClassesEnabled uint32
	FilterComm     uint32
	CommIsAllow    uint32
	FilterPath     uint32
	FilterPort     uint32
	Pad            uint32
}

type wakeWakeExec struct {
	_   structs.HostLayout
	Hdr struct {
		_        structs.HostLayout
		TsNs     uint64
		Kind     uint32
		WireVer  uint32
		Pid      uint32
		Tid      uint32
		Uid      uint32
		Pad      uint32
		CgroupId uint64
		Comm     [16]int8
	}
	Ppid      uint32
	ArgvLen   uint32
	ArgvTrunc uint8
	Pad       [3]uint8
	Filename  [256]int8
	Argv      [512]int8
	_         [4]byte
}

type wakeWakeOpen struct {
	_   structs.HostLayout
	Hdr struct {
		_        structs.HostLayout
		TsNs     uint64
		Kind     uint32
		WireVer  uint32
		Pid      uint32
		Tid      uint32
		Uid      uint32
		Pad      uint32
		CgroupId uint64
		Comm     [16]int8
	}
	Ret       int64
	Flags     int32
	PathTrunc uint8
	Pad       [3]uint8
	Path      [256]int8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	wakeMapCgroupScope      = "cgroup_scope"
	wakeMapCommFilter       = "comm_filter"
	wakeMapDrops            = "drops"
	wakeMapEvents           = "events"
	wakeMapExecScratch      = "exec_scratch"
	wakeMapOpenOut          = "open_out"
	wakeMapOpenPending      = "open_pending"
	wakeMapOpenScratch      = "open_scratch"
	wakeMapPathFilter       = "path_filter"
	wakeMapPortFilter       = "port_filter"
	wakeMapSignalFilter     = "signal_filter"
	wakeMapWakeConfigMap    = "wake_config_map"
	wakeProgWakeExecProg    = "wake_exec_prog"
	wakeProgWakeExitProg    = "wake_exit_prog"
	wakeProgWakeInetState   = "wake_inet_state"
	wakeProgWakeOomProg     = "wake_oom_prog"
	wakeProgWakeOpenatEnter = "wake_openat_enter"
	wakeProgWakeOpenatExit  = "wake_openat_exit"
	wakeProgWakeSignalProg  = "wake_signal_prog"
)

// loadWake returns the embedded CollectionSpec for wake.
func loadWake() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WakeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load wake: %w", err)
	}

	return spec, err
}

// loadWakeObjects loads wake and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*wakeObjects
//	*wakePrograms
//	*wakeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadWakeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadWake()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// wakeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wakeSpecs struct {
	wakeProgramSpecs
	wakeMapSpecs
	wakeVariableSpecs
}

// wakeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wakeProgramSpecs struct {
	WakeExecProg    *ebpf.ProgramSpec `ebpf:"wake_exec_prog"`
	WakeExitProg    *ebpf.ProgramSpec `ebpf:"wake_exit_prog"`
	WakeInetState   *ebpf.ProgramSpec `ebpf:"wake_inet_state"`
	WakeOomProg     *ebpf.ProgramSpec `ebpf:"wake_oom_prog"`
	WakeOpenatEnter *ebpf.ProgramSpec `ebpf:"wake_openat_enter"`
	WakeOpenatExit  *ebpf.ProgramSpec `ebpf:"wake_openat_exit"`
	WakeSignalProg  *ebpf.ProgramSpec `ebpf:"wake_signal_prog"`
}

// wakeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wakeMapSpecs struct {
	CgroupScope   *ebpf.MapSpec `ebpf:"cgroup_scope"`
	CommFilter    *ebpf.MapSpec `ebpf:"comm_filter"`
	Drops         *ebpf.MapSpec `ebpf:"drops"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	ExecScratch   *ebpf.MapSpec `ebpf:"exec_scratch"`
	OpenOut       *ebpf.MapSpec `ebpf:"open_out"`
	OpenPending   *ebpf.MapSpec `ebpf:"open_pending"`
	OpenScratch   *ebpf.MapSpec `ebpf:"open_scratch"`
	PathFilter    *ebpf.MapSpec `ebpf:"path_filter"`
	PortFilter    *ebpf.MapSpec `ebpf:"port_filter"`
	SignalFilter  *ebpf.MapSpec `ebpf:"signal_filter"`
	WakeConfigMap *ebpf.MapSpec `ebpf:"wake_config_map"`
}

// wakeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type wakeVariableSpecs struct {
}

// wakeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadWakeObjects or ebpf.CollectionSpec.LoadAndAssign.
type wakeObjects struct {
	wakePrograms
	wakeMaps
	wakeVariables
}

func (o *wakeObjects) Close() error {
	return _WakeClose(
		&o.wakePrograms,
		&o.wakeMaps,
	)
}

// wakeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadWakeObjects or ebpf.CollectionSpec.LoadAndAssign.
type wakeMaps struct {
	CgroupScope   *ebpf.Map `ebpf:"cgroup_scope"`
	CommFilter    *ebpf.Map `ebpf:"comm_filter"`
	Drops         *ebpf.Map `ebpf:"drops"`
	Events        *ebpf.Map `ebpf:"events"`
	ExecScratch   *ebpf.Map `ebpf:"exec_scratch"`
	OpenOut       *ebpf.Map `ebpf:"open_out"`
	OpenPending   *ebpf.Map `ebpf:"open_pending"`
	OpenScratch   *ebpf.Map `ebpf:"open_scratch"`
	PathFilter    *ebpf.Map `ebpf:"path_filter"`
	PortFilter    *ebpf.Map `ebpf:"port_filter"`
	SignalFilter  *ebpf.Map `ebpf:"signal_filter"`
	WakeConfigMap *ebpf.Map `ebpf:"wake_config_map"`
}

func (m *wakeMaps) Close() error {
	return _WakeClose(
		m.CgroupScope,
		m.CommFilter,
		m.Drops,
		m.Events,
		m.ExecScratch,
		m.OpenOut,
		m.OpenPending,
		m.OpenScratch,
		m.PathFilter,
		m.PortFilter,
		m.SignalFilter,
		m.WakeConfigMap,
	)
}

// wakeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadWakeObjects or ebpf.CollectionSpec.LoadAndAssign.
type wakeVariables struct {
}

// wakePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadWakeObjects or ebpf.CollectionSpec.LoadAndAssign.
type wakePrograms struct {
	WakeExecProg    *ebpf.Program `ebpf:"wake_exec_prog"`
	WakeExitProg    *ebpf.Program `ebpf:"wake_exit_prog"`
	WakeInetState   *ebpf.Program `ebpf:"wake_inet_state"`
	WakeOomProg     *ebpf.Program `ebpf:"wake_oom_prog"`
	WakeOpenatEnter *ebpf.Program `ebpf:"wake_openat_enter"`
	WakeOpenatExit  *ebpf.Program `ebpf:"wake_openat_exit"`
	WakeSignalProg  *ebpf.Program `ebpf:"wake_signal_prog"`
}

func (p *wakePrograms) Close() error {
	return _WakeClose(
		p.WakeExecProg,
		p.WakeExitProg,
		p.WakeInetState,
		p.WakeOomProg,
		p.WakeOpenatEnter,
		p.WakeOpenatExit,
		p.WakeSignalProg,
	)
}

func _WakeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed wake_bpfel.o
var _WakeBytes []byte
