// Command mkfixture regenerates the reference snapshot in
// testdata/fixtures/reference-snapshot.
//
// The fixture is the only executable artefact Wake offers a consumer
// (SPEC.md §6.2), so it must represent the format faithfully: it exercises
// every event class, including `generic`, which is the shape most likely to
// break a reader and the one a happy-path fixture would omit.
//
// It is generated by the real snapshot.Writer — the same code path a live
// daemon uses — against fixed fake inputs, so its bytes are what the package
// actually produces rather than what someone believed it produced. Everything
// that would otherwise vary (the clock, host state, the proc scrape, the
// config hash) is pinned, so regenerating without a deliberate change is a
// no-op and shows up as an empty diff.
//
// Run it with `make fixture`.
//
// Regenerating is *not* the remedy for a failing schema test. If a test says
// the fixture no longer matches the code, the code changed the serialised form,
// and that is a versioning decision — see CHANGELOG.md, "Before you bump it".
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/MatrixMagician/wake/internal/event"
	"github.com/MatrixMagician/wake/internal/snapshot"
)

// Everything below is fixed so the output is byte-for-byte reproducible.
var (
	// base is the fixture's notional incident time.
	base = time.Date(2026, 8, 2, 14, 20, 0, 0, time.UTC)

	// fixtureID is the published directory name. It is derived from the
	// trigger's firing time, so pinning that pins this.
	firedAt = base.Add(6*time.Second + 998*time.Millisecond)
)

func main() {
	out := flag.String("out", "testdata/fixtures", "directory to write the fixture into")
	flag.Parse()

	if err := run(*out); err != nil {
		fmt.Fprintf(os.Stderr, "mkfixture: %v\n", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	// A fresh snapshot is written into a temporary root and then moved into
	// place, so a failure part-way through cannot leave a half-written fixture
	// committed — the same reasoning the writer itself applies (§1).
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("creating the output directory: %w", err)
	}
	// Staged beside the destination rather than in TMPDIR, because the final
	// step is a rename and a rename cannot cross filesystems.
	staging, err := os.MkdirTemp(outDir, ".wake-fixture-*")
	if err != nil {
		return fmt.Errorf("creating a staging directory: %w", err)
	}
	defer func() { _ = os.RemoveAll(staging) }()

	w := snapshot.NewWriter(staging, fixtureVersion,
		snapshot.WithClock(func() time.Time { return firedAt.Add(514 * time.Millisecond) }),
		snapshot.WithSystemInfoSource(fixedSystemInfo{}),
		snapshot.WithProcSource(fixedProc{}),
	)

	res, err := w.Write(snapshot.Input{
		Events:     events(),
		Drops:      drops(),
		Trigger:    trigger(),
		ConfigHash: fixtureConfigHash,
	})
	if err != nil {
		return fmt.Errorf("writing the fixture snapshot: %w", err)
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("creating the output directory: %w", err)
	}

	dest := filepath.Join(outDir, "reference-snapshot")

	// The fixture directory holds a hand-written README explaining what the
	// fixture is for. It is not generated, so it must survive regeneration —
	// the first version of this tool silently deleted it.
	readme := filepath.Join(dest, "README.md")
	preserved, readErr := os.ReadFile(readme)

	// The committed fixture keeps a stable directory name rather than the
	// generated timestamped one, so that references to it in documentation and
	// tests do not change every time it is regenerated.
	if err := os.RemoveAll(dest); err != nil {
		return fmt.Errorf("clearing the previous fixture: %w", err)
	}
	if err := os.Rename(res.Path, dest); err != nil {
		return fmt.Errorf("publishing the fixture: %w", err)
	}
	// Git cannot store 0700 directories as such; the schema test asserts the
	// mode the *writer* produces, not the mode of the checked-out copy, so make
	// the committed fixture readable rather than fighting the tool.
	if err := os.Chmod(dest, 0o755); err != nil {
		return fmt.Errorf("relaxing the fixture's mode for version control: %w", err)
	}

	if readErr == nil {
		if err := os.WriteFile(readme, preserved, 0o644); err != nil {
			return fmt.Errorf("restoring the fixture README: %w", err)
		}
	}

	fmt.Printf("wrote %s\n", dest)
	fmt.Printf("  %d events across %d classes\n", len(events()), countClasses())
	return nil
}

const (
	// fixtureVersion is a placeholder rather than a real build stamp, so the
	// fixture does not change every time the git description does.
	fixtureVersion = "v0.0.0-fixture"

	// fixtureConfigHash is likewise a placeholder: this fixture has no
	// accompanying wake.toml, and a real-looking hash would invite a reader to
	// try to resolve it.
	fixtureConfigHash = "fixture000000000000000000000000000000000000000000000000000000000"
)

// events returns one event of every class, in the order a real incident would
// produce them. Field values are chosen to exercise the awkward cases a
// consumer must handle rather than only the obvious ones: a truncated argv, a
// failing syscall with an errno, a signal death, a decode failure.
func events() []event.Event {
	i32 := func(v int32) *int32 { return &v }
	i64 := func(v int64) *int64 { return &v }
	i16 := func(v int16) *int16 { return &v }

	svc := event.Enrichment{
		Comm:      "smtpd",
		Ppid:      4300,
		Ancestors: []string{"systemd"},
		Cgroup:    "/system.slice/mstr.service",
		Unit:      "mstr.service",
		User:      "mstr",
	}
	container := event.Enrichment{
		Comm:      "curl",
		Ppid:      5100,
		Ancestors: []string{"sh", "conmon", "systemd"},
		Cgroup:    "/machine.slice/libpod-2e7d2c03a9507ae265ecf5b5356885a53393a2029d241394997265a1a25aefc6.scope",
		Unit:      "libpod-2e7d2c03a9507ae265ecf5b5356885a53393a2029d241394997265a1a25aefc6.scope",
		Container: "2e7d2c03a9507ae265ecf5b5356885a53393a2029d241394997265a1a25aefc6",
		User:      "root",
	}

	return []event.Event{
		// exec, with argv present and untruncated.
		{
			Timestamp: base.Add(1 * time.Second), Class: event.ClassExec,
			PID: 4321, TID: 4321, UID: 987, CgroupID: 4021,
			Enrichment: svc,
			Filename:   "/usr/sbin/smtpd",
			Argv:       []string{"smtpd", "-d", "--config=/etc/mstr/smtpd.conf"},
		},
		// open, failing: the interesting case, and the one carrying an errno.
		{
			Timestamp: base.Add(2 * time.Second), Class: event.ClassOpen,
			PID: 4321, TID: 4321, UID: 987, CgroupID: 4021,
			Enrichment: svc,
			Path:       "/etc/ssl/private/mstr.pem",
			Flags:      "O_RDONLY|O_CLOEXEC",
			Ret:        i64(-13),
			Errno:      "EACCES",
		},
		// connect, failing, from inside a container: exercises the enrichment
		// triple and the state-transition rendering at once.
		{
			Timestamp: base.Add(3 * time.Second), Class: event.ClassConnect,
			PID: 5123, TID: 5123, UID: 0, CgroupID: 7714,
			Enrichment: container,
			SAddr:      "10.88.0.4", DAddr: "10.0.4.7",
			SPort: 54321, DPort: 587,
			Proto:    "tcp",
			OldState: "TCP_SYN_SENT", NewState: "TCP_CLOSE",
			Errno: "ECONNREFUSED_OR_TIMEOUT",
		},
		// signal: delivery, with a sender.
		{
			Timestamp: base.Add(4 * time.Second), Class: event.ClassSignal,
			PID: 4321, TID: 4321, UID: 987, CgroupID: 4021,
			Enrichment: svc,
			Signal:     i32(15), SignalName: "SIGTERM", SenderPID: i32(1),
		},
		// generic: a record the decoder did not recognise, kept rather than
		// dropped. A consumer that mishandles this class mishandles exactly the
		// situation Wake exists to make visible.
		{
			Timestamp: base.Add(5 * time.Second), Class: event.ClassGeneric,
			PID: 4321, TID: 4321, UID: 987, CgroupID: 4021,
			Enrichment:  svc,
			RawKind:     99,
			Raw:         []byte{0xde, 0xad, 0xbe, 0xef},
			DecodeError: "unknown kind 99",
		},
		// oom: a kill, with the memory figures the tracepoint reports.
		{
			Timestamp: base.Add(6 * time.Second), Class: event.ClassOOM,
			PID: 5123, TID: 5123, UID: 0, CgroupID: 7714,
			Enrichment:  container,
			TotalVM:     8388608,
			AnonRSS:     7340032,
			FileRSS:     131072,
			OOMScoreAdj: i16(0),
		},
		// exec with a truncated argv, so a consumer sees the flag set at least
		// once rather than only in the documentation.
		{
			Timestamp: base.Add(6*time.Second + 500*time.Millisecond), Class: event.ClassExec,
			PID: 4400, TID: 4400, UID: 987, CgroupID: 4021,
			Enrichment: svc,
			Filename:   "/usr/bin/java",
			Argv:       []string{"java", "-Xmx4g", "-Dvery.long.property=aaaaaaaaaaaaaaaaaaaa"},
			ArgvTrunc:  true,
		},
		// exit: death by signal, which is what fired the trigger.
		{
			Timestamp: firedAt,
			Class:     event.ClassExit,
			PID:       4321, TID: 4321, UID: 987, CgroupID: 4021,
			Enrichment: svc,
			ExitCode:   i32(0),
			ExitSignal: i32(9),
			SignalName: "SIGKILL",
		},
	}
}

func countClasses() int {
	seen := map[event.Class]bool{}
	for _, e := range events() {
		seen[e.Class] = true
	}
	return len(seen)
}

// drops deliberately reports a non-zero userspace_ring count. A fixture with an
// all-zero drop report would let a consumer satisfy obligation §6.3 by
// accident, never having seen a snapshot that admits to losing anything.
func drops() event.DropReport {
	d := &event.Drops{}
	d.Set(event.BoundaryRing, event.ClassOpen, 12)
	return d.Report()
}

func trigger() snapshot.TriggerInfo {
	pid := int32(4321)
	return snapshot.TriggerInfo{
		Type:    "watched-process",
		Reason:  "smtpd (pid 4321) was killed by SIGKILL",
		Rule:    "mstr-crash",
		PID:     &pid,
		Unit:    "mstr.service",
		FiredAt: firedAt,
	}
}

// fixedSystemInfo returns host state that never varies, so system.json is
// reproducible. The values describe a plausible machine rather than this one.
type fixedSystemInfo struct{}

func (fixedSystemInfo) Capture() (snapshot.SystemInfo, error) {
	return snapshot.SystemInfo{
		CapturedAt: firedAt.Add(500 * time.Millisecond),
		Uname: snapshot.Uname{
			Sysname: "Linux", Nodename: "mstr-prod-07",
			Release: "6.10.0-1.fc42.x86_64",
			Version: "#1 SMP PREEMPT_DYNAMIC Fri Jul 18 12:00:00 UTC 2026",
			Machine: "x86_64",
		},
		MemInfo: map[string]string{
			"MemTotal":     "16065536 kB",
			"MemAvailable": "412300 kB",
			"SwapTotal":    "8388604 kB",
			"SwapFree":     "0 kB",
		},
		Pressure: map[string]snapshot.PSILines{
			"memory": {
				Some: map[string]string{
					"avg10": "42.11", "avg60": "38.02", "avg300": "12.55", "total": "8123456",
				},
				Full: map[string]string{
					"avg10": "21.00", "avg60": "18.44", "avg300": "6.10", "total": "4011223",
				},
			},
		},
		Uptime:  864123.45,
		LoadAvg: [3]float64{8.14, 6.02, 3.77},
	}, nil
}

// fixedProc returns a proc scrape for the triggering process. Note what is
// absent: no file contents behind any fd, only the fd number and its symlink
// target, per the privacy line in docs/snapshot-format.md §5.1.
type fixedProc struct{}

func (fixedProc) Scrape(pid int32) (map[string][]byte, map[string]string, bool, error) {
	files := map[string][]byte{
		"status": []byte("Name:\tsmtpd\nState:\tR (running)\n" +
			fmt.Sprintf("Pid:\t%d\n", pid) +
			"PPid:\t4300\nThreads:\t4\nVmRSS:\t   65432 kB\n"),
		"limits": []byte("Limit                     Soft Limit           Hard Limit           Units\n" +
			"Max open files            1024                 524288               files\n"),
		"cgroup":  []byte("0::/system.slice/mstr.service\n"),
		"cmdline": []byte("smtpd\x00-d\x00--config=/etc/mstr/smtpd.conf\x00"),
	}
	fds := map[string]string{
		"0": "/dev/null",
		"1": "socket:[48213]",
		"2": "/var/log/mstr/error.log",
		"3": "pipe:[48214]",
	}
	return files, fds, true, nil
}
